In [1]:
import numpy as np

In [4]:
def merge_sort(vetor):
    if len(vetor) > 1:
        divisao = len(vetor) // 2
        esquerda = vetor[:divisao].copy()
        direita = vetor[divisao:].copy()
        
        merge_sort(esquerda)
        merge_sort(direita)
        
        i = j = k = 0
        
        # Ordena esquerda e direita
        while i < len(esquerda) and j < len(direita):
            if esquerda[i] < direita[j]:
                vetor[k] = esquerda[i]
                i += 1
            else:
                vetor[k] = direita[j]
                j += 1
            k += 1
            
        # Ordenação final
        while i < len(esquerda):
            vetor[k] = esquerda[i]
            i += 1
            k += 1
        while j < len(direita):
            vetor[k] = direita[j]
            j += 1
            k += 1
    return vetor

In [5]:
merge_sort(np.array([15, 34, 8, 3]))

array([ 3,  8, 15, 34])

In [6]:
merge_sort(np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1]))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
merge_sort(np.array([38, 27, 43, 9, 82, 10]))

array([ 9, 10, 27, 38, 43, 82])