In [1]:
import numpy as np

In [2]:
def shell_sort(vetor):
    intervalo = len(vetor) // 2
    
    while intervalo > 0:
        for i in range(intervalo, len(vetor)):
            temp = vetor[i]
            j = i
            while j >= intervalo and vetor[j - intervalo] > temp:
                vetor[j] = vetor[j - intervalo]
                j -= intervalo
            vetor[j] = temp
        intervalo //= 2
    
    return vetor

In [3]:
shell_sort(np.array([15, 34, 8, 3]))

array([ 3,  8, 15, 34])

In [4]:
shell_sort(np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1]))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
shell_sort(np.array([8, 5, 1, 4, 2, 3]))

array([1, 2, 3, 4, 5, 8])