In [1]:
import numpy as np

In [7]:
class FilaPrioridade:
    def __init__(self, capacidade):
        self.capacidade = capacidade
        self.numero_elementos = 0
        self.valores = np.empty(self.capacidade, dtype = int)
        
    def fila_vazia(self):
        return self.numero_elementos == 0
    
    def fila_cheia(self):
        return self.numero_elementos == self.capacidade
    
    def primeiro(self):
        if self.fila_vazia():
            return -1
        return self.valores[self.numero_elementos - 1]
    
    def enfileirar(self, valor):
        if self.fila_cheia():
            print('A fila está cheia')
            return
        
        if self.numero_elementos == 0:
            self.valores[self.numero_elementos] = valor
            self.numero_elementos += 1
        else:
            x = self.numero_elementos - 1
            while x >= 0:
                if valor > self.valores[x]:
                    self.valores[x + 1] = self.valores[x]
                else:
                    break
                x -= 1
            
            self.valores[x + 1] = valor
            self.numero_elementos += 1   
    
    def desenfileirar(self):
        if self.fila_vazia():
            print('A fila está vazia')
            return
        
        valor = self.valores[self.numero_elementos - 1]
        self.numero_elementos -= 1
        return valor

In [8]:
fila = FilaPrioridade(5)

In [9]:
print(fila.primeiro())

-1


In [10]:
# 30
fila.enfileirar(30)
print(fila.primeiro())

30


In [11]:
# 50 30
fila.enfileirar(50)
print(fila.primeiro())

30


In [12]:
# 50 30 10
fila.enfileirar(10)
print(fila.primeiro())

10


In [13]:
print(fila.valores)

[50 30 10  0  1]


In [14]:
# 50 40 30 10
fila.enfileirar(40)
print(fila.primeiro())

10


In [15]:
print(fila.valores)

[50 40 30 10  1]


In [16]:
# 50 40 30 20 10
fila.enfileirar(20)
print(fila.primeiro())

10


In [17]:
print(fila.valores)

[50 40 30 20 10]


In [18]:
fila.enfileirar(2)

A fila está cheia


In [19]:
fila.desenfileirar()
print(fila.primeiro())

20


In [20]:
fila.desenfileirar()
print(fila.primeiro())

30


In [21]:
fila.desenfileirar()
print(fila.primeiro())

40


In [22]:
print(fila.valores)

[50 40 30 20 10]


In [25]:
fila.enfileirar(5)
print(fila.primeiro())

5


In [26]:
print(fila.valores)

[50 40  5  5  5]
