In [1]:
import math

In [2]:
import numpy as np

In [3]:
class Bag:
    def __init__(self, capacidade):
        self.__capacidade = capacidade        
        self.__valores = np.zeros(self.__capacidade)
        self.__tamanho = 0
        
    def __iter__(self):
        self.__indice = 0 
        return self
    
    def __next__(self):
        if self.__indice < self.__tamanho:
            valor = self.__valores[self.__indice]
            self.__indice += 1
            return valor
        else:
            raise StopIteration
        
    def isFull(self):
        return self.__tamanho == self.__capacidade 
    
    def add(self, valor):
        if self.isFull():
            print('The bag is full!')
            return
        if self.__valores[self.__tamanho] == 0:
            self.__valores[self.__tamanho] = valor
            self.__tamanho += 1
        
    def viewBag(self):
        return print(self.__valores)
    
    def bagSize(self):
        return self.__tamanho

In [4]:
bag = Bag(10)

In [5]:
bag.isFull()

False

In [6]:
bag.viewBag()

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
bag.add(1)
bag.add(8)
bag.add(5)
bag.add(3)
bag.add(9)
bag.add(2)

In [8]:
bag.viewBag()

[1. 8. 5. 3. 9. 2. 0. 0. 0. 0.]


In [9]:
bag.isFull()

False

In [10]:
bag.add(10)

In [11]:
bag.viewBag()

[ 1.  8.  5.  3.  9.  2. 10.  0.  0.  0.]


In [12]:
soma = 0
for item in bag:
    soma += item

In [13]:
print(soma)

38.0


In [14]:
mean = soma / bag.bagSize()
print(mean)

5.428571428571429


In [15]:
soma = 0
for item in bag:
    soma += (item - mean) * (item - mean)
std = math.sqrt(soma / (bag.bagSize() - 1))
print(std)

3.598941643369749
