In [1]:
import numpy as np

In [2]:
matriz = np.array([[2, 3, 1],
                   [4, 5, 7]])

In [3]:
print(matriz)

[[2 3 1]
 [4 5 7]]


In [4]:
print(matriz.shape)

(2, 3)


In [6]:
print(matriz[0])

[2 3 1]


In [7]:
print(matriz[1])

[4 5 7]


In [8]:
print(matriz[0][0])

2


In [10]:
print(matriz[0][1])

3


In [11]:
print(matriz[1][0])

4


In [13]:
for i in range(matriz.shape[0]):
    print(matriz[i])
    for j in range(matriz.shape[1]):
        print(matriz[i][j])

[2 3 1]
2
3
1
[4 5 7]
4
5
7
